# Generated by Django 4.2.11 on 2024-09-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
    ]
