# Generated by Django 4.2.11 on 2024-09-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_remove_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='roadmaps/'),
        ),
    ]
